_target_: src.models.CNN
_recursive_: False
n_classes: 10
channels: [10, 10, 10]
local_kernel_size: 3
hidden_dims: [160, 100]
padding: 1
bias: False
verbose: False
optimizer_cfg:
  _target_: torch.optim.Adam
  lr: .001