_target_: src.models.CNN1d
_recursive_: False
n_classes: 10
in_channels: 64
channels: [128, 128, 128]
local_kernel_size: 6
hidden_dims: [1024, 100]
padding: 3
bias: True
batchnorm: True
verbose: False
optimizer_cfg:
  _target_: torch.optim.Adam
  lr: .001