defaults:
  - model_cfg: DenseNet
  - data_cfg: CIFAR10
  - loggers@trainer_cfg: Default
  - callbacks@trainer_cfg: Default
  - override hydra/launcher: submitit_slurm
  #- override hydra/sweeper: ax
  - _self_

experiment_id: test_dense_cifar10
ckpt_path: ${hydra:runtime.cwd}/results/train/train_dense_cifar/2021-12-06/21-31-07/logs/default/version_0/checkpoints/checkpoint_epoch=28.ckpt

hydra:
  run:
    dir: ./results/train/${experiment_id}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: ${hydra.run.dir}

  launcher:
    partition: gaia
    nodes: ${trainer_cfg.num_nodes}
    tasks_per_node: ${trainer_cfg.gpus}
    constraint: xeon-g6
    timeout_min: 1000000
    additional_parameters:
      gres: gpu:volta:2
      exclusive: True

trainer_cfg:
  _target_: pytorch_lightning.Trainer
  num_nodes: 1
  gpus: 2
  strategy: ddp
  precision: 16
  max_epochs: 1000

model_cfg:
  in_dim: 3072

data_cfg:
  datamodule:
    num_workers: 20